/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom8.ui;

import java.awt.print.PrinterException;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import nhom8.dao.InDao;
import nhom8.helper.DateHelper;

/**
 *
 * @author Asus
 */
public class InJIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form PrintJIFrame
     */
    public InJIFrame(String ma) {
        initComponents();      
        this.printHoaDon(ma);
    }
    InDao inDao = new InDao();
    
    
    
    void printHoaDon(String maHD){  
        DecimalFormat df = new DecimalFormat("#,###,##0.00");
        List<Object[]> list = inDao.selectHoaDon(maHD);
        double tongtien = 0;
        String tenNV = (String) list.get(0)[3];
        String date = DateHelper.toString((Date) list.get(0)[4]);
      
          txtView.setText("\t\t  CỬA HÀNG XE MÁY TVT\n\n"
                + "Mã Hóa Đơn: "+maHD
                + "\n==========================================================\n"
                + "STT\tLoại xe\t\tSố khung \tĐơn giá\n\n");
                  
         for (int i = 0; i < list.size(); i++) {
             
            txtView.append(i+1+"\t"+list.get(i)[0]+"\t\t"+list.get(i)[1]+" \t"+df.format(list.get(i)[2])+"\n\n");
               tongtien = tongtien + Double.parseDouble(list.get(i)[2]+"");
        }
        

//                + "1\tXeMáy\t\tSK1214341\t100000\n\n"
//                + "2\tXeOto\t\tSK12143415\t1000005\n\n"
                        
          txtView.append(
                 "===========================================================\n"
                + "Ngày "+date+"\t\t\t\tThành Tiền\n"
                + "  (Người bán)\t\t\t\t"+df.format(tongtien)+"(vnđ)\n\n"
                + tenNV);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtView = new javax.swing.JTextArea();
        btnCanCel = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        txtView.setColumns(5);
        txtView.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        txtView.setRows(5);
        txtView.setToolTipText("");
        jScrollPane1.setViewportView(txtView);

        btnCanCel.setText("CANCEL");
        btnCanCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanCelActionPerformed(evt);
            }
        });

        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnCanCel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCanCel)
                    .addComponent(btnPrint))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCanCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanCelActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnCanCelActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
            txtView.print();
        } catch (PrinterException ex) {
            Logger.getLogger(InJIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCanCel;
    private javax.swing.JButton btnPrint;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtView;
    // End of variables declaration//GEN-END:variables
}
