/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom8.ui;

import java.awt.Toolkit;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.Timer;

public class MainJFrame extends javax.swing.JFrame {

    LoginJIFrame loginJIFrame;
    DoiMKJIFrame doiMKJIFrame;
    KhachHangJIFrame khachHangJIFrame;
    HangVaLoaiJIFrame hangVaLoaiJIFrame;
    XeJIFrame xeJIFrame;
    NhanVienJIFrame nhanVienJIFrame;
    BanHangJIFrame banHangJIFrame;

    public MainJFrame() {
       
        initComponents();     
        //set fullsize
        Toolkit tk = Toolkit.getDefaultToolkit();
        int width = (int) tk.getScreenSize().getWidth();
        int height = (int) tk.getScreenSize().getHeight();
        this.setSize(width, height);
        //dong hô
        new Timer(1000, new ActionListener() {
            SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a");

            @Override
            public void actionPerformed(ActionEvent ae) {
                lblDonHo.setText(format.format(new Date()));
            }
        }).start();
        //dăng nhap

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane(){

            ImageIcon icon  = new ImageIcon(this.getClass().getResource("/nhom8/icon/hinhnen.jpg"));
            Image img = icon.getImage();
            @Override
            protected void paintComponent(Graphics g) {
                g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            }
        };
        lblDonHo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDangNhap = new javax.swing.JMenuItem();
        mniDoiMK = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniThoat = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mniHang_LoaiXe = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniXe = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniKhachHang = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniNhanVien = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mniDoanhThuThang = new javax.swing.JMenuItem();
        mniDoanhThuNam = new javax.swing.JMenuItem();
        mnuNghiepVu = new javax.swing.JMenu();
        mniBanHang = new javax.swing.JMenuItem();
        mniNhapHang = new javax.swing.JMenuItem();
        mnuTroGiup = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDonHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom8/icon/Alarm.png"))); // NOI18N
        lblDonHo.setText("11:11:30");

        Desktop.setLayer(lblDonHo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DesktopLayout.createSequentialGroup()
                .addContainerGap(802, Short.MAX_VALUE)
                .addComponent(lblDonHo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDonHo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(426, Short.MAX_VALUE))
        );

        mnuHeThong.setText("Hệ Thống");

        mniDangNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mniDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom8/icon/Boy.png"))); // NOI18N
        mniDangNhap.setText("Đăng nhập");
        mniDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangNhapActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangNhap);

        mniDoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom8/icon/Key.png"))); // NOI18N
        mniDoiMK.setText("Đổi mật khẩu");
        mniDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMKActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDoiMK);
        mnuHeThong.add(jSeparator1);

        mniThoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mniThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom8/icon/Stop.png"))); // NOI18N
        mniThoat.setText("Thoát");
        mniThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThoatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniThoat);

        jMenuBar1.add(mnuHeThong);

        mnuQuanLy.setText("Quản Lý");

        mniHang_LoaiXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom8/icon/RSS.png"))); // NOI18N
        mniHang_LoaiXe.setText("Hãng & loại xe");
        mniHang_LoaiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHang_LoaiXeActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniHang_LoaiXe);
        mnuQuanLy.add(jSeparator5);

        mniXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom8/icon/Peace.png"))); // NOI18N
        mniXe.setText("Xe");
        mniXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniXeActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniXe);
        mnuQuanLy.add(jSeparator4);

        mniKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom8/icon/Clien list.png"))); // NOI18N
        mniKhachHang.setText("Khách hàng");
        mniKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKhachHangActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniKhachHang);
        mnuQuanLy.add(jSeparator3);
        mnuQuanLy.add(jSeparator2);

        mniNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        mniNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom8/icon/Conference.png"))); // NOI18N
        mniNhanVien.setText("Nhân viên");
        mniNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniNhanVien);

        jMenuBar1.add(mnuQuanLy);

        mnuThongKe.setText("Thống Kê");

        mniDoanhThuThang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom8/icon/Dollar.png"))); // NOI18N
        mniDoanhThuThang.setText("Doanh thu theo tháng");
        mniDoanhThuThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoanhThuThangActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniDoanhThuThang);

        mniDoanhThuNam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom8/icon/Coin.png"))); // NOI18N
        mniDoanhThuNam.setText("Doanh thu theo năm");
        mniDoanhThuNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoanhThuNamActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniDoanhThuNam);

        jMenuBar1.add(mnuThongKe);

        mnuNghiepVu.setText("Nghiệp Vụ");

        mniBanHang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mniBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom8/icon/Basket.png"))); // NOI18N
        mniBanHang.setText("Bán hàng");
        mniBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBanHangActionPerformed(evt);
            }
        });
        mnuNghiepVu.add(mniBanHang);

        mniNhapHang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mniNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom8/icon/Properties.png"))); // NOI18N
        mniNhapHang.setText("Nhập hàng");
        mniNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhapHangActionPerformed(evt);
            }
        });
        mnuNghiepVu.add(mniNhapHang);

        jMenuBar1.add(mnuNghiepVu);

        mnuTroGiup.setText("Trợ Giúp");
        jMenuBar1.add(mnuTroGiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMKActionPerformed
        if (doiMKJIFrame == null || doiMKJIFrame.isClosed()) {
            doiMKJIFrame = new DoiMKJIFrame();
            Desktop.add(doiMKJIFrame).setVisible(true);

        }
    }//GEN-LAST:event_mniDoiMKActionPerformed

    private void mniDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangNhapActionPerformed

        if (loginJIFrame == null || loginJIFrame.isClosed()) {
            loginJIFrame = new LoginJIFrame();
            loginJIFrame.addInternalFrameListener(new InternalFrameListener() {
                @Override
                public void internalFrameOpened(InternalFrameEvent ife) {
                    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public void internalFrameClosing(InternalFrameEvent ife) {
                    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public void internalFrameClosed(InternalFrameEvent ife) {
                    mniDangNhap.setText("Đăng Xuất");
                }

                @Override
                public void internalFrameIconified(InternalFrameEvent ife) {
                    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public void internalFrameDeiconified(InternalFrameEvent ife) {
                    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public void internalFrameActivated(InternalFrameEvent ife) {
                    mniDangNhap.setText("Đăng Nhập");
                }

                @Override
                public void internalFrameDeactivated(InternalFrameEvent ife) {
                    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }
            });
            Desktop.add(loginJIFrame);
            loginJIFrame.setLocation(Desktop.getWidth() / 2 - loginJIFrame.getWidth() / 2,
                    Desktop.getHeight() / 2 - loginJIFrame.getHeight() / 2);
            loginJIFrame.setVisible(true);
        }


    }//GEN-LAST:event_mniDangNhapActionPerformed

    private void mniThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniThoatActionPerformed

    private void mniKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKhachHangActionPerformed
        if (khachHangJIFrame == null || khachHangJIFrame.isClosed()) {
            khachHangJIFrame = new KhachHangJIFrame(Desktop);
            Desktop.add(khachHangJIFrame);
//                khachHangJIFrame.setLocation(this.getWidth()/2 - khachHangJIFrame.getWidth()/2,
//                this.getHeight()/2 - khachHangJIFrame.getHeight()/2 );
            khachHangJIFrame.setVisible(true);
        }
    }//GEN-LAST:event_mniKhachHangActionPerformed

    private void mniHang_LoaiXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHang_LoaiXeActionPerformed
        if (hangVaLoaiJIFrame == null || hangVaLoaiJIFrame.isClosed()) {
            hangVaLoaiJIFrame = new HangVaLoaiJIFrame();
            Desktop.add(hangVaLoaiJIFrame).setVisible(true);
        }
    }//GEN-LAST:event_mniHang_LoaiXeActionPerformed

    private void mniXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniXeActionPerformed
        if (xeJIFrame == null || xeJIFrame.isClosed()) {
            xeJIFrame = new XeJIFrame();
//            xeJIFrame.setLocation(this.getWidth() / 2 - xeJIFrame.getWidth() / 2,
//                    this.getHeight() / 2 - xeJIFrame.getHeight() / 2);
            Desktop.add(xeJIFrame).setVisible(true);
        }
    }//GEN-LAST:event_mniXeActionPerformed

    private void mniNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanVienActionPerformed
        if (nhanVienJIFrame == null || nhanVienJIFrame.isClosed()) {
            nhanVienJIFrame = new NhanVienJIFrame();
            Desktop.add(nhanVienJIFrame);
            nhanVienJIFrame.setVisible(true);
        }
    }//GEN-LAST:event_mniNhanVienActionPerformed

    private void mniDoanhThuThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoanhThuThangActionPerformed
  
            DoanhThuJIFrame doanhThuJIFrame = new DoanhThuJIFrame(0);
            Desktop.add(doanhThuJIFrame);
            doanhThuJIFrame.setLocation(Desktop.getWidth() / 2 - doanhThuJIFrame.getWidth() / 2,
                    Desktop.getHeight() / 2 - doanhThuJIFrame.getHeight() / 2);
            doanhThuJIFrame.setVisible(true);
        
    }//GEN-LAST:event_mniDoanhThuThangActionPerformed

    private void mniBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBanHangActionPerformed
        if (banHangJIFrame == null || banHangJIFrame.isClosed()) {
            banHangJIFrame = new BanHangJIFrame(Desktop,null);
            Desktop.add(banHangJIFrame).setVisible(true);;
        }


    }//GEN-LAST:event_mniBanHangActionPerformed

    private void mniNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhapHangActionPerformed
        NhapHangJIFrame nhapKhoJIFrame = new NhapHangJIFrame();
        Desktop.add(nhapKhoJIFrame);
//            nhapKhoJIFrame.setLocation(Desktop.getWidth()/2 - nhapKhoJIFrame.getWidth()/2,
//                Desktop.getHeight()/2 - nhapKhoJIFrame.getHeight()/2 );
        nhapKhoJIFrame.setVisible(true);
    }//GEN-LAST:event_mniNhapHangActionPerformed

    private void mniDoanhThuNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoanhThuNamActionPerformed
        DoanhThuJIFrame doanhThuJIFrame = new DoanhThuJIFrame(1);
            Desktop.add(doanhThuJIFrame);
            doanhThuJIFrame.setLocation(Desktop.getWidth() / 2 - doanhThuJIFrame.getWidth() / 2,
                    Desktop.getHeight() / 2 - doanhThuJIFrame.getHeight() / 2);
            doanhThuJIFrame.setVisible(true);
    }//GEN-LAST:event_mniDoanhThuNamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JLabel lblDonHo;
    private javax.swing.JMenuItem mniBanHang;
    private javax.swing.JMenuItem mniDangNhap;
    private javax.swing.JMenuItem mniDoanhThuNam;
    private javax.swing.JMenuItem mniDoanhThuThang;
    private javax.swing.JMenuItem mniDoiMK;
    private javax.swing.JMenuItem mniHang_LoaiXe;
    private javax.swing.JMenuItem mniKhachHang;
    private javax.swing.JMenuItem mniNhanVien;
    private javax.swing.JMenuItem mniNhapHang;
    private javax.swing.JMenuItem mniThoat;
    private javax.swing.JMenuItem mniXe;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuNghiepVu;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenu mnuTroGiup;
    // End of variables declaration//GEN-END:variables
}
